name: tubes
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.9+2
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.8
  http: ^1.0.0
  url_launcher: ^6.0.10
  google_nav_bar: ^5.0.7
  shared_preferences: ^2.0.0
  curved_navigation_bar: ^1.0.0
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  flutter_html: ^3.0.0-alpha.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  firebase_messaging: ^15.2.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Uncomment and add assets if you need them
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment and add custom fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  assets:
    - assets/images/my_logo.jpg
    - assets/images/batman.jpg
    - assets/images/rabbids.jpg

# Optional: Add localization support if required
# flutter_localizations:
#   sdk: flutter
